# Application configuration
application-name: gen_ai_training

spring:
  main:
    eb-application-type: none

client:
  azureopenai:
    key: ${AZURE_CLIENT_KEY}
    endpoint: ${CLIENT_ENDPOINT}
    deployment-name: gpt-4o